name: Run Notebook on Update

on:
  push:
    paths:
      - 'Rules/**/*.sql'

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Execute Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute Scripts/CICD.ipynb --output Scripts/CICD.ipynb

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Scripts/CICD.ipynb
          git commit -m "Execute Jupyter notebook" || echo "No changes to commit"
          git push origin || echo "No changes to push"
        env:
          TOKENGIT: ${{ secrets.TOKENGIT }}
