name: Run Notebook on Update

on:
  push:
    paths:
      - 'Rules/**/*.sql'

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          
      - name: Create Output directory
        run: mkdir -p $GITHUB_WORKSPACE/Output

      - name: Execute Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute Scripts/CICD.ipynb --output $GITHUB_WORKSPACE/Output/CICD.ipynb 

      
        env:
          TOKENGIT: ${{ secrets.TOKENGIT }}
