name: Run Notebook on Update

on:
  push:
    paths:
      - 'Rules/**/*.sql'

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert

      - name: Execute Jupyter notebook
        run: |
          jupyter nbconvert --to notebook --execute Scripts/CICD.ipynb --output Output/CICD.ipynb

      
        env:
          TOKENGIT: ${{ secrets.TOKENGIT }}
