name: Run Python Script on Update in Rules Folder

on:
  push:
    paths:
      - 'Rules/**/*.sql'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # If you have any dependencies

      - name: Run Python Script
        run: python Scripts/GitAutoMationPOCCodeWithComments.py # Replace with your script's path
